server:
  port: 8090
logging:
  file:
    name: logs/application.log
  level:
    root: INFO
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testpsql
    username: pruebapsqluser
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
