server:
  port: 8080
logging:
  file:
    name: logs/application.log
  level:
    root: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
    Linktic.Test.ProductCatalogService.: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testpsql
    username: pruebapsqluser
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    urls[0]:
      name: 'name'
      url: '/v3/api-docs'
  cache:
    disabled: true